# Network Security Configuration for InErgize
# Implements zero-trust networking with micro-segmentation

version: '3.8'

# Custom networks with security controls
networks:
  # DMZ network for external-facing services
  inergize-dmz:
    driver: bridge
    name: inergize-dmz
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

  # Internal application network
  inergize-app:
    driver: bridge
    name: inergize-app
    ipam:
      driver: default
      config:
        - subnet: 172.20.2.0/24
          gateway: 172.20.2.1
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"

  # Database network (most restricted)
  inergize-data:
    driver: bridge
    name: inergize-data
    ipam:
      driver: default
      config:
        - subnet: 172.20.3.0/24
          gateway: 172.20.3.1
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"

  # Monitoring network
  inergize-monitoring:
    driver: bridge
    name: inergize-monitoring
    ipam:
      driver: default
      config:
        - subnet: 172.20.4.0/24
          gateway: 172.20.4.1

services:
  # Network Security Gateway
  security-gateway:
    image: inergize/security-gateway:latest
    container_name: inergize-security-gateway
    restart: unless-stopped
    networks:
      inergize-dmz:
        ipv4_address: 172.20.1.10
      inergize-app:
        ipv4_address: 172.20.2.10
    ports:
      - "443:443"   # HTTPS only
      - "80:80"     # HTTP redirect to HTTPS
    environment:
      - SSL_CERT_PATH=/etc/ssl/certs/inergize.crt
      - SSL_KEY_PATH=/etc/ssl/private/inergize.key
      - ENABLE_WAF=true
      - WAF_RULES_PATH=/etc/waf/rules
      - DDoS_PROTECTION=true
      - RATE_LIMIT_REQUESTS=1000
      - RATE_LIMIT_WINDOW=3600
    volumes:
      - ./infrastructure/security/ssl:/etc/ssl:ro
      - ./infrastructure/security/waf:/etc/waf:ro
      - ./logs/security:/var/log/security
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  # TLS Termination Proxy
  tls-proxy:
    image: nginx:alpine
    container_name: inergize-tls-proxy
    restart: unless-stopped
    networks:
      inergize-dmz:
        ipv4_address: 172.20.1.11
    ports:
      - "8443:443"
    volumes:
      - ./infrastructure/security/nginx-tls.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/security/ssl:/etc/ssl:ro
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=50m
      - /var/run:noexec,nosuid,size=10m

  # Network Intrusion Detection System
  intrusion-detection:
    image: securityonion/suricata:latest
    container_name: inergize-ids
    restart: unless-stopped
    networks:
      inergize-monitoring:
        ipv4_address: 172.20.4.10
    volumes:
      - ./infrastructure/security/suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./infrastructure/security/rules:/etc/suricata/rules:ro
      - ./logs/ids:/var/log/suricata
    environment:
      - INTERFACE=eth0
      - HOME_NET=172.20.0.0/16
      - EXTERNAL_NET=any
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - no-new-privileges:true

  # Network monitoring and traffic analysis
  network-monitor:
    image: ntopng/ntopng:stable
    container_name: inergize-network-monitor
    restart: unless-stopped
    networks:
      inergize-monitoring:
        ipv4_address: 172.20.4.11
    ports:
      - "3001:3000"  # ntopng web interface
    volumes:
      - ./infrastructure/security/ntopng.conf:/etc/ntopng/ntopng.conf:ro
      - ./data/ntopng:/var/lib/ntopng
    environment:
      - NTOPNG_CONFIG_FILE=/etc/ntopng/ntopng.conf
    security_opt:
      - no-new-privileges:true

  # VPN Gateway for secure remote access
  vpn-gateway:
    image: kylemanna/openvpn:latest
    container_name: inergize-vpn
    restart: unless-stopped
    networks:
      inergize-dmz:
        ipv4_address: 172.20.1.12
    ports:
      - "1194:1194/udp"
    volumes:
      - ./infrastructure/security/openvpn:/etc/openvpn
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      - OVPN_SERVER_URL=vpn.inergize.com
      - OVPN_AUTH_TYPE=cert

  # Firewall and traffic filtering
  network-firewall:
    image: inergize/iptables-firewall:latest
    container_name: inergize-firewall
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./infrastructure/security/firewall-rules.sh:/usr/local/bin/firewall-rules.sh:ro
    environment:
      - DMZ_SUBNET=172.20.1.0/24
      - APP_SUBNET=172.20.2.0/24
      - DATA_SUBNET=172.20.3.0/24
      - MONITORING_SUBNET=172.20.4.0/24
    command: ["/usr/local/bin/firewall-rules.sh"]

# Security labels for network tracking
labels:
  - "security.network.segmentation=enabled"
  - "security.network.encryption=tls-1.3"
  - "security.network.ids=suricata"
  - "security.network.monitoring=ntopng"