# InErgize Kong Production Configuration
# Enterprise-grade setup with security, monitoring, and LinkedIn compliance
_format_version: "3.0"

# Consumers for different client applications
consumers:
  - username: web-app
    custom_id: web-client-001
    tags: ["web", "trusted"]
  
  - username: mobile-app
    custom_id: mobile-client-001
    tags: ["mobile", "trusted"]
  
  - username: admin-panel
    custom_id: admin-client-001
    tags: ["admin", "privileged"]

# API Keys for consumer authentication
key_auths:
  - consumer: web-app
    key: "web_app_secure_key_prod_001"
    tags: ["web-access"]
  
  - consumer: mobile-app
    key: "mobile_app_secure_key_prod_001"
    tags: ["mobile-access"]
  
  - consumer: admin-panel
    key: "admin_secure_key_prod_001"
    tags: ["admin-access"]

# JWT credentials for token-based authentication
jwt_secrets:
  - consumer: web-app
    key: "web-app-issuer"
    secret: "web_jwt_secret_change_in_production"
    algorithm: "HS256"
  
  - consumer: mobile-app
    key: "mobile-app-issuer" 
    secret: "mobile_jwt_secret_change_in_production"
    algorithm: "HS256"
  
  - consumer: admin-panel
    key: "admin-issuer"
    secret: "admin_jwt_secret_change_in_production"
    algorithm: "HS256"

# Enhanced service definitions with health checks and circuit breakers
services:
  - name: auth-service
    url: http://inergize-auth-service:3001
    connect_timeout: 5000
    write_timeout: 30000
    read_timeout: 30000
    retries: 3
    tags: ["auth", "core"]
    
  - name: user-service
    url: http://inergize-user-service:3002
    connect_timeout: 5000
    write_timeout: 30000
    read_timeout: 30000
    retries: 3
    tags: ["user", "core"]
    
  - name: linkedin-service
    url: http://inergize-linkedin-service:3003
    connect_timeout: 10000
    write_timeout: 60000
    read_timeout: 60000
    retries: 2
    tags: ["linkedin", "integration"]
    
  - name: analytics-service
    url: http://inergize-analytics-service:3004
    connect_timeout: 5000
    write_timeout: 30000
    read_timeout: 30000
    retries: 3
    tags: ["analytics", "core"]
    
  - name: ai-service
    url: http://inergize-ai-service:3005
    connect_timeout: 15000
    write_timeout: 120000
    read_timeout: 120000
    retries: 1
    tags: ["ai", "integration"]

# Enhanced routing with versioning and load balancing
routes:
  # Auth Service Routes with enhanced security
  - name: auth-login
    service: auth-service
    paths: ["/api/v1/auth/login"]
    methods: ["POST"]
    strip_path: true
    preserve_host: false
    tags: ["auth", "public"]
    
  - name: auth-register
    service: auth-service
    paths: ["/api/v1/auth/register"]
    methods: ["POST"]
    strip_path: true
    preserve_host: false
    tags: ["auth", "public"]
    
  - name: auth-protected
    service: auth-service
    paths: ["/api/v1/auth"]
    methods: ["GET", "PUT", "DELETE"]
    strip_path: true
    preserve_host: false
    tags: ["auth", "protected"]

  # User Service Routes
  - name: user-routes
    service: user-service
    paths: ["/api/v1/users"]
    methods: ["GET", "PUT", "DELETE", "PATCH"]
    strip_path: true
    preserve_host: false
    tags: ["user", "protected"]

  # LinkedIn Service Routes with specialized rate limiting
  - name: linkedin-oauth
    service: linkedin-service
    paths: ["/api/v1/linkedin/oauth"]
    methods: ["GET", "POST"]
    strip_path: true
    preserve_host: false
    tags: ["linkedin", "oauth"]
    
  - name: linkedin-api
    service: linkedin-service
    paths: ["/api/v1/linkedin"]
    methods: ["GET", "POST", "PUT", "DELETE"]
    strip_path: true
    preserve_host: false
    tags: ["linkedin", "protected"]

  # Analytics Service Routes with caching
  - name: analytics-realtime
    service: analytics-service
    paths: ["/api/v1/analytics/realtime"]
    methods: ["GET"]
    strip_path: true
    preserve_host: false
    tags: ["analytics", "realtime"]
    
  - name: analytics-api
    service: analytics-service
    paths: ["/api/v1/analytics"]
    methods: ["GET", "POST"]
    strip_path: true
    preserve_host: false
    tags: ["analytics", "protected"]

  # AI Service Routes with extended timeouts
  - name: ai-content
    service: ai-service
    paths: ["/api/v1/ai/content"]
    methods: ["POST"]
    strip_path: true
    preserve_host: false
    tags: ["ai", "generation"]
    
  - name: ai-banners
    service: ai-service
    paths: ["/api/v1/ai/banners"]
    methods: ["POST", "GET"]
    strip_path: true
    preserve_host: false
    tags: ["ai", "generation"]

# Enhanced global plugins with production configurations
plugins:
  # Advanced CORS with origin validation
  - name: cors
    config:
      origins:
        - "https://inergize.com"
        - "https://www.inergize.com"
        - "https://app.inergize.com"
        - "https://dashboard.inergize.com"
      methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
      headers:
        - "Accept"
        - "Accept-Version"
        - "Content-Length"
        - "Content-Type"
        - "Date"
        - "Authorization"
        - "X-Auth-Token"
        - "X-Request-ID"
        - "X-API-Key"
      exposed_headers:
        - "X-Auth-Token"
        - "X-RateLimit-Remaining"
        - "X-Request-ID"
      credentials: true
      max_age: 3600
      preflight_continue: false

  # Comprehensive security headers
  - name: response-transformer
    config:
      add:
        headers:
          - "X-Content-Type-Options: nosniff"
          - "X-Frame-Options: DENY"
          - "X-XSS-Protection: 1; mode=block"
          - "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
          - "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
          - "Referrer-Policy: strict-origin-when-cross-origin"
          - "Permissions-Policy: geolocation=(), microphone=(), camera=()"

  # Request/Response logging with structured format
  - name: file-log
    config:
      path: "/tmp/kong-access.log"
      custom_fields_by_lua:
        request_id: "return kong.ctx.shared.request_id"
        user_id: "return kong.ctx.shared.authenticated_user_id"
        subscription_tier: "return kong.ctx.shared.user_subscription"

  # Request ID generation
  - name: correlation-id
    config:
      header_name: "X-Request-ID"
      generator: "uuid"
      echo_downstream: true

# Route-specific plugins
- route: auth-login
  plugins:
    - name: rate-limiting
      config:
        minute: 5
        hour: 20
        day: 100
        policy: local
        hide_client_headers: false
        fault_tolerant: true

- route: auth-register  
  plugins:
    - name: rate-limiting
      config:
        minute: 2
        hour: 10
        day: 20
        policy: local
        hide_client_headers: false
        fault_tolerant: true

- route: linkedin-api
  plugins:
    - name: rate-limiting
      config:
        minute: 20
        hour: 100
        day: 500
        policy: local
        hide_client_headers: false
        fault_tolerant: true
    - name: proxy-cache
      config:
        response_code: [200, 301, 404]
        request_method: ["GET", "HEAD"]
        content_type: ["application/json"]
        cache_ttl: 300
        strategy: memory

- route: analytics-realtime
  plugins:
    - name: rate-limiting
      config:
        minute: 60
        hour: 1000
        day: 10000
        policy: local
        hide_client_headers: false
        fault_tolerant: true

- route: ai-content
  plugins:
    - name: rate-limiting
      config:
        minute: 5
        hour: 50
        day: 200
        policy: local
        hide_client_headers: false
        fault_tolerant: true
    - name: request-size-limiting
      config:
        allowed_payload_size: 5

# Service-level plugins for authentication
- service: user-service
  plugins:
    - name: jwt
      config:
        uri_param_names: ["jwt"]
        cookie_names: ["jwt"]
        header_names: ["Authorization"]
        key_claim_name: "iss"
        secret_is_base64: false
        run_on_preflight: true

- service: linkedin-service
  plugins:
    - name: jwt
      config:
        uri_param_names: ["jwt"]
        cookie_names: ["jwt"]
        header_names: ["Authorization"]
        key_claim_name: "iss"
        secret_is_base64: false
        run_on_preflight: true

- service: analytics-service
  plugins:
    - name: jwt
      config:
        uri_param_names: ["jwt"]
        cookie_names: ["jwt"]
        header_names: ["Authorization"]
        key_claim_name: "iss"
        secret_is_base64: false
        run_on_preflight: true

- service: ai-service
  plugins:
    - name: jwt
      config:
        uri_param_names: ["jwt"]
        cookie_names: ["jwt"]
        header_names: ["Authorization"]
        key_claim_name: "iss"
        secret_is_base64: false
        run_on_preflight: true

# Advanced Load Balancing and Health Checks
upstreams:
  - name: auth-upstream
    algorithm: round-robin
    hash_on: none
    hash_fallback: none
    hash_on_cookie_path: /
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 10
          http_statuses: [200, 302]
          successes: 2
        unhealthy:
          interval: 10
          http_statuses: [429, 404, 500, 501, 502, 503, 504, 505]
          tcp_failures: 2
          timeouts: 3
          http_failures: 5
      passive:
        type: http
        healthy:
          http_statuses: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 306, 307, 308]
          successes: 5
        unhealthy:
          http_statuses: [429, 500, 503]
          tcp_failures: 2
          timeouts: 7
          http_failures: 5

  - name: user-upstream
    algorithm: round-robin
    hash_on: none
    hash_fallback: none
    hash_on_cookie_path: /
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 10
          http_statuses: [200, 302]
          successes: 2
        unhealthy:
          interval: 10
          http_statuses: [429, 404, 500, 501, 502, 503, 504, 505]
          tcp_failures: 2
          timeouts: 3
          http_failures: 5
      passive:
        type: http
        healthy:
          http_statuses: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 306, 307, 308]
          successes: 5
        unhealthy:
          http_statuses: [429, 500, 503]
          tcp_failures: 2
          timeouts: 7
          http_failures: 5

  - name: linkedin-upstream
    algorithm: least-connections
    hash_on: none
    hash_fallback: none
    hash_on_cookie_path: /
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 15
          http_statuses: [200, 302]
          successes: 2
        unhealthy:
          interval: 15
          http_statuses: [429, 404, 500, 501, 502, 503, 504, 505]
          tcp_failures: 2
          timeouts: 5
          http_failures: 3
      passive:
        type: http
        healthy:
          http_statuses: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 306, 307, 308]
          successes: 3
        unhealthy:
          http_statuses: [429, 500, 503]
          tcp_failures: 2
          timeouts: 5
          http_failures: 3

  - name: analytics-upstream
    algorithm: round-robin
    hash_on: none
    hash_fallback: none
    hash_on_cookie_path: /
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 10
          http_statuses: [200, 302]
          successes: 2
        unhealthy:
          interval: 10
          http_statuses: [429, 404, 500, 501, 502, 503, 504, 505]
          tcp_failures: 2
          timeouts: 3
          http_failures: 5
      passive:
        type: http
        healthy:
          http_statuses: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 306, 307, 308]
          successes: 5
        unhealthy:
          http_statuses: [429, 500, 503]
          tcp_failures: 2
          timeouts: 7
          http_failures: 5

  - name: ai-upstream
    algorithm: least-connections
    hash_on: none
    hash_fallback: none
    hash_on_cookie_path: /
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 30
          http_statuses: [200, 302]
          successes: 2
        unhealthy:
          interval: 30
          http_statuses: [429, 404, 500, 501, 502, 503, 504, 505]
          tcp_failures: 2
          timeouts: 10
          http_failures: 3
      passive:
        type: http
        healthy:
          http_statuses: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 306, 307, 308]
          successes: 3
        unhealthy:
          http_statuses: [429, 500, 503]
          tcp_failures: 2
          timeouts: 10
          http_failures: 3

# Upstream targets for load balancing
targets:
  - target: inergize-auth-service:3001
    upstream: auth-upstream
    weight: 100

  - target: inergize-user-service:3002
    upstream: user-upstream
    weight: 100

  - target: inergize-linkedin-service:3003
    upstream: linkedin-upstream
    weight: 100

  - target: inergize-analytics-service:3004
    upstream: analytics-upstream
    weight: 100

  - target: inergize-ai-service:3005
    upstream: ai-upstream
    weight: 100

# Global performance and reliability plugins
global_plugins:
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

  - name: tcp-log
    config:
      host: elasticsearch
      port: 9200
      timeout: 10000
      keepalive: 60000

  - name: zipkin
    config:
      http_endpoint: "http://zipkin:9411/api/v2/spans"
      sample_ratio: 0.001
      include_credential: true
      traceid_byte_count: 16
      spanid_byte_count: 8
      default_service_name: "kong-gateway"

  - name: bot-detection
    config:
      allow: []
      deny: ["python-requests", "curl", "wget", "scrapy", "bot", "crawler", "spider"]

  - name: ip-restriction
    config:
      allow: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
      deny: []