# Kong API Gateway Enterprise Configuration for InErgize Backend
# Optimized for 10,000+ concurrent users with enterprise-grade security and performance

_format_version: "3.0"
_transform: true

services:
  # Auth Service Load Balancer
  - name: auth-service
    url: http://auth-service-1:3001
    protocol: http
    host: auth-service-1
    port: 3001
    path: /
    retries: 3
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - auth
      - microservice

  # LinkedIn Service Load Balancer
  - name: linkedin-service
    url: http://linkedin-service-1:3003
    protocol: http
    host: linkedin-service-1
    port: 3003
    path: /
    retries: 3
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - linkedin
      - microservice

  # Analytics Service Load Balancer
  - name: analytics-service
    url: http://analytics-service-1:3004
    protocol: http
    host: analytics-service-1
    port: 3004
    path: /
    retries: 3
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - analytics
      - microservice

upstreams:
  # Auth Service Upstream with Load Balancing
  - name: auth-upstream
    algorithm: round-robin
    hash_on: none
    hash_fallback: none
    healthchecks:
      active:
        timeout: 10
        concurrency: 5
        http_path: "/health"
        healthy:
          interval: 30
          http_statuses: [200, 302]
          successes: 2
        unhealthy:
          interval: 30
          http_statuses: [429, 500, 502, 503, 504]
          http_failures: 3
    tags:
      - auth
      - load-balancer

routes:
  # Auth Service Routes
  - name: auth-login
    service: auth-service
    protocols: [http, https]
    methods: [POST]
    paths: ["/api/auth/login"]
    strip_path: false
    preserve_host: false
    tags:
      - auth
      - login

  # LinkedIn Service Routes
  - name: linkedin-automation
    service: linkedin-service
    protocols: [http, https]
    methods: [GET, POST, PUT, DELETE]
    paths: ["/api/linkedin/automation"]
    strip_path: false
    preserve_host: false
    tags:
      - linkedin
      - automation

plugins:
  # Global Rate Limiting
  - name: rate-limiting
    config:
      minute: 1000
      hour: 50000
      day: 500000
      policy: redis
      redis_host: redis-master
      redis_port: 6379
      redis_password: ${REDIS_PASSWORD}
      redis_database: 2
      hide_client_headers: false
    tags:
      - global
      - rate-limiting

  # Global CORS
  - name: cors
    config:
      origins:
        - https://app.inergize.com
        - https://inergize.com
        - http://localhost:3000
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
        - X-Auth-Token
        - X-User-ID
      credentials: true
      max_age: 3600
    tags:
      - global
      - cors