# Prometheus configuration for InErgize Platform
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: 'inergize-cluster'
    environment: '${ENVIRONMENT}'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules files
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s

  # Kong API Gateway metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics
    scrape_interval: 15s

  # Application services
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'linkedin-service'
    static_configs:
      - targets: ['linkedin-service:3003']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:3004']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3005']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s

  - job_name: 'scheduler-service'
    static_configs:
      - targets: ['scheduler-service:3006']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 5s

  - job_name: 'automation-service'
    static_configs:
      - targets: ['automation-service:3007']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 5s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3008']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 5s

  # Web application metrics
  - job_name: 'web-app'
    static_configs:
      - targets: ['web-app:3000']
    metrics_path: /api/metrics
    scrape_interval: 30s
    scrape_timeout: 5s

  # Custom application metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['analytics-service:3005']
    metrics_path: /business-metrics
    scrape_interval: 60s
    scrape_timeout: 10s

# Remote write configuration (for long-term storage)
remote_write:
  - url: "${PROMETHEUS_REMOTE_WRITE_URL}"
    basic_auth:
      username: "${PROMETHEUS_REMOTE_WRITE_USERNAME}"
      password: "${PROMETHEUS_REMOTE_WRITE_PASSWORD}"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    path: /prometheus/data