# Prometheus Configuration for InErgize Security Monitoring
# Comprehensive metrics collection for security, performance, and compliance

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'inergize-production'
    environment: '${ENVIRONMENT:-production}'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

# Load alert rules
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # InErgize Services
  - job_name: 'auth-service'
    static_configs:
      - targets: ['inergize-auth-service:3001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'auth-service'

  - job_name: 'user-service'
    static_configs:
      - targets: ['inergize-user-service:3002']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'user-service'

  - job_name: 'linkedin-service'
    static_configs:
      - targets: ['inergize-linkedin-service:3003']
    scrape_interval: 30s  # Less frequent due to rate limiting
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'linkedin-service'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['inergize-analytics-service:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'analytics-service'

  - job_name: 'ai-service'
    static_configs:
      - targets: ['inergize-ai-service:3005']
    scrape_interval: 30s  # Less frequent due to AI service load
    metrics_path: /metrics
    scrape_timeout: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'ai-service'

  # Kong API Gateway
  - job_name: 'kong'
    static_configs:
      - targets: ['inergize-kong:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'kong-gateway'

  # Database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Blackbox monitoring (endpoint health)
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://inergize-kong:8000/health
        - https://inergize-kong:8443/health
        - http://inergize-auth-service:3001/health
        - http://inergize-user-service:3002/health
        - http://inergize-linkedin-service:3003/health
        - http://inergize-analytics-service:3004/health
        - http://inergize-ai-service:3005/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Security event metrics
  - job_name: 'security-processor'
    static_configs:
      - targets: ['security-processor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s